In [12]:
!pip install sklearn

Collecting sklearn
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

WARNING: Ignoring invalid distribution -orch (c:\users\sanjay\appdata\local\programs\python\python310\lib\site-packages)
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [15 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.

  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Failed to build 'sklearn' when getting requirements to build wheel

In [13]:
import pandas as pd
import io
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [37]:
Customer_detail=pd.read_csv("Churn_Modelling.csv")
Customer_detail.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [38]:
#Customer_detail.isnull().sum()
#Customer_detail.drop_duplicates(inplace=True)
#Customer_detail.dropna(inplace=True)
Customer_detail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [39]:
Customer_detail.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [40]:
Customer_detail.nunique()

RowNumber          10000
CustomerId         10000
Surname             2932
CreditScore          460
Geography              3
Gender                 2
Age                   70
Tenure                11
Balance             6382
NumOfProducts          4
HasCrCard              2
IsActiveMember         2
EstimatedSalary     9999
Exited                 2
dtype: int64

In [41]:
print(Customer_detail.columns)

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [42]:
Customer_detail.drop(["CustomerId","Surname","Age","Geography","Gender"],axis=1,inplace=True)

In [43]:
Customer_detail.head()

,RowNumber,CreditScore,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,619,2,0.00,1,1,1,101348.88,1
1,2,608,1,83807.86,1,0,1,112542.58,0
2,3,502,8,159660.80,3,1,0,113931.57,1
3,4,699,1,0.00,2,0,0,93826.63,0
4,5,850,2,125510.82,1,1,1,79084.10,0

In [45]:
Customer_detail.describe().round()

,RowNumber,CreditScore,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0
mean,5000.0,651.0,5.0,76486.0,2.0,1.0,1.0,100090.0,0.0
std,2887.0,97.0,3.0,62397.0,1.0,0.0,0.0,57510.0,0.0
min,1.0,350.0,0.0,0.0,1.0,0.0,0.0,12.0,0.0
25%,2501.0,584.0,3.0,0.0,1.0,0.0,0.0,51002.0,0.0
50%,5000.0,652.0,5.0,97199.0,1.0,1.0,1.0,100194.0,0.0
75%,7500.0,718.0,7.0,127644.0,2.0,1.0,1.0,149388.0,0.0
max,10000.0,850.0,10.0,250898.0,4.0,1.0,1.0,199992.0,1.0

In [48]:
scaler = StandardScaler()
Detail2= pd.DataFrame(scaler.fit_transform(Customer_detail)).round(2)
Detail2

         0     1     2     3     4     5     6     7     8
0    -1.73 -0.33 -1.04 -1.23 -0.91  0.65  0.97  0.02  1.98
1    -1.73 -0.44 -1.39  0.12 -0.91 -1.55  0.97  0.22 -0.51
2    -1.73 -1.54  1.03  1.33  2.53  0.65 -1.03  0.24  1.98
3    -1.73  0.50 -1.39 -1.23  0.81 -1.55 -1.03 -0.11 -0.51
4    -1.73  2.06 -1.04  0.79 -0.91  0.65  0.97 -0.37 -0.51
...    ...   ...   ...   ...   ...   ...   ...   ...   ...
9995  1.73  1.25 -0.00 -1.23  0.81  0.65 -1.03 -0.07 -0.51
9996  1.73 -1.39  1.72 -0.31 -0.91  0.65  0.97  0.03 -0.51
9997  1.73  0.60  0.69 -1.23 -0.91 -1.55  0.97 -1.01  1.98
9998  1.73  1.26 -0.70 -0.02  0.81  0.65 -1.03 -0.13  1.98
9999  1.73  1.46 -0.35  0.86 -0.91  0.65 -1.03 -1.08 -0.51

[10000 rows x 9 columns]

In [50]:
x=Detail2.iloc[:,:-1].values
x

array([[-1.73, -0.33, -1.04, ...,  0.65,  0.97,  0.02],
       [-1.73, -0.44, -1.39, ..., -1.55,  0.97,  0.22],
       [-1.73, -1.54,  1.03, ...,  0.65, -1.03,  0.24],
       ...,
       [ 1.73,  0.6 ,  0.69, ..., -1.55,  0.97, -1.01],
       [ 1.73,  1.26, -0.7 , ...,  0.65, -1.03, -0.13],
       [ 1.73,  1.46, -0.35, ...,  0.65, -1.03, -1.08]], shape=(10000, 8))

In [51]:
y=Detail2.iloc[:,-1].values
y

array([ 1.98, -0.51,  1.98, ...,  1.98,  1.98, -0.51], shape=(10000,))

In [53]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
print(x_train)
print(len(x_train))
print(x_test)
print(len(x_test))

[[-0.49 -0.39  0.69 ...  0.65 -1.03 -0.69]
 [-1.03  0.18  0.69 ... -1.55 -1.03  0.11]
 [-1.63 -0.7   0.69 ...  0.65 -1.03 -0.85]
 ...
 [ 0.27  1.06 -0.35 ... -1.55  0.97  0.81]
 [-0.57  0.1  -0.   ...  0.65  0.97 -0.49]
 [ 1.51  1.57  1.38 ...  0.65  0.97  0.6 ]]
8000
[[ 0.2  -0.43 -1.04 ...  0.65 -1.03 -1.58]
 [ 0.46 -0.22  1.03 ...  0.65  0.97 -0.16]
 [-1.1   2.06 -0.35 ...  0.65  0.97  1.08]
 ...
 [ 0.51 -0.03 -0.   ...  0.65 -1.03  0.87]
 [-0.8  -1.37  1.72 ...  0.65  0.97  1.08]
 [ 0.09  0.93  1.38 ... -1.55  0.97 -0.06]]
2000